### ISSUE TITLE
Windows 10 commands not handled

### ISSUE THREAD

**Issue by Timurinyo** [The-HeX/mcpe-geometry-generator#1]
Builded solution using VS2017. After launch and connection to wsserver the software output is https://imgur.com/a/OdfHp
Any commands listed in readme doesn't work. Only hotkeys such as ctrl+... are handled - https://imgur.com/a/OdfHp
Other commands seems to be blocked by Minecraft. (Think so because of the in-game message: unknown command...) Can you help please?

**Comment by erichexter** [comment]
Sorry for not documenting this correctly. The commands do not need the slash before the command. 
so you can just type 

create  box  width length height block

**Comment by Timurinyo** [comment]
Thanks for reply. But even when using "create box 10 10 10 5" there is no any response from app

**Comment by eduelfie** [comment]
I too have this issue, but I am using it with Minecraft: Education Edition, and I believe they may have 'restricted' the ports that are allowed in via a wsserver, is there a place I can change the port to be the same as what Code Connection uses, as we know that is open?

**Comment by erichexter** [comment]
There currently is not a way to change the port, but it would be a really simple code change..  If you are building the project you can change this line here to modify the port. https://github.com/The-HeX/minecraft-worldedit-bedrock/blob/master/src/WorldEdit/Program.cs#L35

**Comment by Timurinyo** [comment]
I am also using Minecraft:Education Edition. I changed the port as erichexter suggests, but still no success. After typing /wsserver 127.0.0.1:19131 (code connection port) or 127.0.0.1:12112 in Minecraft chat, WorldEdit console says: "opened, subscribing to PlayerMessage" but Minecraft says "Couldn't connect to server". So the port is not a problem or at least not the only one. Maybe there is some specific connecting procedure for education edition. May be some specific message should be sent from server. @erichexter May be we can somehow figure out what's going on during the connection?

**Comment by erichexter** [comment]
My guess is that there may have been some changes to the message for the
1.2 release.  What version of MC edu are you using?  I have not tested the
code since the 1.2 release, its something I need to do, to see if there was
a breaking change to the message formats


Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by inventortimer** [comment]
Everything works fine for last version of windows 10 edition. But no success for education edition.

**Comment by Timurinyo** [comment]
Dear, Eric. There is an minecraft:EE [API description](https://education.minecraft.net/wp-content/uploads/Code_Connection_API.pdf)  with an [example](https://github.com/Mojang/mojang.github.io) of code in js.  Can you take a look and say if it's possible to modify your world editor to work with Educational version of the game?

**Comment by erichexter** [comment]
Yes I will take a look at it.


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by erichexter** [comment]
So, I initially developed this using the Code Builder. There were some capabilities that it does not support, so I do not want to use that going forward.  I am also converting this code to javascript so that I can provide a behavior pack using the new 1.8 scripting api. so that should make this simpler once that is released for the edu version.
