### ISSUE TITLE
Download Plz?

### ISSUE THREAD

**Issue by KingRainbow44** [The-HeX/mcpe-geometry-generator#3]
I want to try this out, but I can't I can't find the worldedit.exe file in the master! Please, release a version, I want to share this on YouTube too! If you do release this, it is going to be amazing!

**Comment by texhex99** [comment]
same problem

**Comment by erichexter** [comment]
I just published a release here  https://github.com/The-HeX/minecraft-worldedit-bedrock/releases/tag/0.1
