### ISSUE TITLE
How do you import and export schematics?

### ISSUE THREAD

**Issue by KingRainbow44** [The-HeX/mcpe-geometry-generator#4]
Im wondering, how do you import and export schematics?

**Comment by erichexter** [comment]
There is a setting in the config file where the app looks for schematic files, update that setting, run the server, drop some schematic in the folder, run the import command to import, for large schematics you need to afk, the import will tp you around as it imports layers.

**Comment by erichexter** [comment]
This cannot export schematics, the api is not available in Minecraft yet. I use medit unified to export.
