### ISSUE TITLE
Installing into Minecraft

### ISSUE THREAD

**Issue by Sojjer-py** [The-HeX/mcpe-geometry-generator#6]
I have downloaded all files and am not sure how to get this into minecraft. Please help.

**Comment by LoneSimba** [comment]
It's all said it the readme. But it doesn't seem to work for me either.

**Comment by LoneSimba** [comment]
@FaZeSojjer after some reseach i can say one thing - this project is abandoned. Buuut there's a branch (https://github.com/carltoncolter/minecraft-worldedit-bedrock), which might be working, i'll give it a try and post there

**Comment by LoneSimba** [comment]
wellp, it doesn't seem to be working either
too bad

**Comment by erichexter** [comment]
Can you give me some information on what you tried and what did not work?  what version of minecraft you are using,, ect?

**Comment by CtrlAltCuteness** [comment]
@erichexter Minecraft (Bedrock) has changed a lot since 11 months ago. Also, does it even specify what platform(s) this requires in the readme file?

**Comment by erichexter** [comment]
@CtrlAltCuteness thanks for pointing this out, it is Windows only executable. I’ll update the reader to be more explicit.

 Although bedrock has changed this still works the same, I just tested it against 1.7.2 and 1.9 beta.  The connection to the bedrock webhooks is a little flaky, sometimes it takes running the connect command multiple times to connect, but once it is connected everything else is fine.
