### ISSUE TITLE
WS Connect error

### ISSUE THREAD

**Issue by Noobcrafteryt** [The-HeX/mcpe-geometry-generator#7]
/wsserver 127.0.0.1:12112

Cannot connect.

**Comment by KingRainbow44** [comment]
@Noobcrafteryt try using /connect localhost:12112

**Comment by MiguelArmendariz** [comment]
Not working for me

**Comment by delsaranbigglesworth** [comment]
This is also not working for me either. I ran netstat -a in CMD and it's open and listening. /connect localhost:12112 also didn't work for me.

**Comment by erichexter** [comment]
you need to make sure that cheats are enabled on your world.

**Comment by erichexter** [comment]
closing to work with this on a single issue #8
