### ISSUE TITLE
NuGet files missing

### ISSUE THREAD

**Issue by delsaranbigglesworth** [The-HeX/mcpe-geometry-generator#9]
What Nuget file should I put in to get? I see xunitcore is one but its not telling me the other in VS. I was just going to compile a copy and see if I could get this working.

**Comment by erichexter** [comment]
Sorry I totally missed this .. i will pull down the repository and see what I have missing in the proj file.  I will probably just port this to dot net core.

**Comment by erichexter** [comment]
I just loaded up the project in VS 2019 it built and ran from a clean repository, it should auto download the nuget packages in pagkages.config.
